#! /usr/bin/env bash
set -e

# dependencies
apt-get update
apt-get install -y build-essential curl git jq libpq-dev libsqlite3-dev libsasl2-dev libssl-dev postgresql-client postgresql postgresql-contrib sudo vim zlib1g-dev supervisor
apt-get clean

echo "\nDone installing dependencies...\n"
