#! /usr/bin/env bash
set -e

# dependencies
apt-get update
apt-get install -y curl git libpq-dev libsqlite3-dev libsasl2-dev postgresql-client postgresql postgresql-contrib sudo vim zlib1g-dev supervisor
apt-get clean

# install node version manager nvm for scripting stellar configuration
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.9/install.sh | bash

# make nvm available on commandline now...
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# install node and npm
nvm install --lts
nvm use --lts

echo "\nDone installing dependencies...\n"
