#! /usr/bin/env bash
set -e

export STELLAR_HOME="/opt/stellar"
export PGHOME="$STELLAR_HOME/postgresql"
export SUPHOME="$STELLAR_HOME/supervisor"
export COREHOME="$STELLAR_HOME/core"
export HZHOME="$STELLAR_HOME/horizon"
export BRIDGEHOME="$STELLAR_HOME/bridge"
export COMPLIANCEHOME="$STELLAR_HOME/compliance"
export SCRIPTSHOME="$STELLAR_HOME/scripts"

export PGBIN="/usr/lib/postgresql/9.4/bin"
export PGDATA="$PGHOME/data"
export PGUSER="stellar"
export PGPORT=5432

QUICKSTART_INITIALIZED=false
CURRENT_POSTGRES_PID=""

function main() {
	echo ""
	echo "Starting Research Stellar"
	echo ""

	process_args $*

	echo "mode: $STELLAR_MODE"
	echo "network: $NETWORK ($NETWORK_PASSPHRASE)"

	copy_defaults
	#init_scripts
	init_db
	init_stellar_core
	init_horizon
	init_bridge
	init_compliance
	copy_pgpass

	stop_postgres  # this gets started in init_db

	# launch services
	exec_supervisor
}

function process_args() {
	while [[ -n "$1" ]]; do
  	ARG="$1"
	  shift


	  case "${ARG}" in
	  --testnet)
	    NETWORK="testnet"
	    ;;
	  --pubnet)
	    NETWORK="pubnet"
	    ;;
	  --standalone)
	    NETWORK="standalone"
	    ;;
	  --bank0)
	    NETWORK="bank0"
		;;
	  --bank1)
	    NETWORK="bank1"
		;;
	  --bank2)
	    NETWORK="bank2"
		;;
	  *)
	    echo "Unknown container arg $ARG" >&2
	    exit 1
	  esac
	done

	# TODO: ask for what network to use
	if [ -z "$NETWORK" ]; then
		NETWORK="testnet"
	fi

	case "$NETWORK" in
	testnet)
    export NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
    ;;
	pubnet)
    export NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
    ;;
	standalone)
    export NETWORK_PASSPHRASE="Standalone Network ; February 2017"
    ;;
	bank0)
	export NETWORK_PASSPHRASE="My Network ; March 2018"
	;;
	bank1)
	export NETWORK_PASSPHRASE="My Network ; March 2018"
	;;
	bank2)
	export NETWORK_PASSPHRASE="My Network ; March 2018"
	;;
	*)
		echo "Unknown network: '$NETWORK'" >&2
		exit 1
	esac

	# Are we ephemeral or persistent?
	if [ -z "$STELLAR_MODE" ]; then
		if [ -f "/opt/stellar/.docker-ephemeral" ]; then
			STELLAR_MODE="ephemeral"
		else
			STELLAR_MODE="persistent"
		fi
	fi
}

function set_pg_password() {

	if [ -n "$POSTGRES_PASSWORD" ]; then
		PGPASS=$POSTGRES_PASSWORD
		echo "using POSTGRES_PASSWORD"
		return 0
	fi

	# use a random password when ephemeral (or some other unknown mode)
	if [ "$STELLAR_MODE" != "persistent" ]; then
		PGPASS=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' |  head -c 16)
		echo "postgres password: $PGPASS"
		return 0
	fi

	if [ -n "$PGPASS" ]; then
		echo "postgres password: $PGPASS"
		return 0
	fi

	# ask for a password when persistent
	read -s -p "Enter New Postgresql Password: " PGPASS
	echo ""
	read -s -p "Confirm: " PGPASS_CONFIRMATION
	echo ""

	if [ -z "$PGPASS" ]; then
		echo "Password empty" >&2
		exit 1
	fi

	if [ "$PGPASS" != "$PGPASS_CONFIRMATION" ]; then
		echo "Password mistmach" >&2
		exit 1
	fi

}

function copy_defaults() {
	local CP="rsync -a"

	if [ -d $PGHOME/etc ]; then
		echo "postgres: config directory exists, skipping copy"
	else
		$CP /opt/stellar-default/common/postgresql/ $PGHOME
	fi

	if [ -d $SUPHOME/etc ]; then
		echo "supervisor: config directory exists, skipping copy"
	else
		$CP /opt/stellar-default/common/supervisor/ $SUPHOME
	fi

	if [ -d $COREHOME/etc ]; then
		echo "stellar-core: config directory exists, skipping copy"
	else
		$CP /opt/stellar-default/common/core/ $COREHOME
		$CP /opt/stellar-default/$NETWORK/core/ $COREHOME
	fi

	if [ -d $HZHOME/etc ]; then
		echo "horizon: config directory exists, skipping copy"
	else
		$CP /opt/stellar-default/common/horizon/ $HZHOME
	fi

	if [ -d $BRIDGEHOME/etc ]; then
		echo "bridge: config directory exists, skipping copy"
	else
		if [ -d /opt/stellar-default/$NETWORK/bridge ]; then
			$CP /opt/stellar-default/common/bridge/ $BRIDGEHOME
			$CP /opt/stellar-default/$NETWORK/bridge/ $BRIDGEHOME
		fi
	fi

	if [ -d $COMPLIANCEHOME/etc ]; then
		echo "compliance: config directory exists, skipping copy"
	else
		if [ -d /opt/stellar-default/$NETWORK/compliance ]; then
			$CP /opt/stellar-default/common/compliance/ $COMPLIANCEHOME
			$CP /opt/stellar-default/$NETWORK/compliance/ $COMPLIANCEHOME
		fi
	fi

	if [ -d $SCRIPTSHOME ]; then
		echo "scripts: directory exists, skipping copy"
	else
		$CP /opt/stellar-default/common/scripts/ $SCRIPTSHOME
	fi			
}

function copy_pgpass() {
	local CP="rsync -a"

	$CP /opt/stellar/postgresql/.pgpass /root/
	chmod 0600 /root/.pgpass

	$CP /opt/stellar/postgresql/.pgpass /home/stellar
	chmod 0600 /home/stellar/.pgpass
	chown stellar:stellar /home/stellar/.pgpass
}

function init_scripts() {
	if [ -f $SCRIPTSHOME/.scripts-initialized ]; then
		echo "scripts: already initialized"
		return 0
	fi
	pushd $SCRIPTSHOME

	npm install --save stellar-sdk

	touch .scripts-initialized
	popd
}

function init_db() {
	if [ -f $PGHOME/.quickstart-initialized ]; then
		echo "postgres: already initialized"
		return 0
	fi
	pushd $PGHOME

	# workaround!!!! from: https://github.com/nimiq/docker-postgresql93/issues/2
	mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private
	# end workaround

	echo "postgres user: $PGUSER"

	set_pg_password

	run_silent "finalize-pgpass" sed -ri "s/__PGPASS__/$PGPASS/g" /opt/stellar/postgresql/.pgpass

	mkdir -p $PGDATA
	chown postgres:postgres $PGDATA
	chmod 0700 $PGDATA

	run_silent "init-postgres" sudo -u postgres $PGBIN/initdb -D $PGDATA

	start_postgres
	run_silent "create-compliance-db" sudo -u postgres createdb compliance
	run_silent "create-bridge-db" sudo -u postgres createdb bridge
	run_silent "create-horizon-db" sudo -u postgres createdb horizon
	run_silent "create-core-db" sudo -u postgres createdb core
	run_silent "stellar-postgres-user" sudo -u postgres psql <<-SQL
		CREATE USER $PGUSER WITH PASSWORD '$PGPASS';
		GRANT ALL PRIVILEGES ON DATABASE compliance to $PGUSER;
		GRANT ALL PRIVILEGES ON DATABASE bridge to $PGUSER;
		GRANT ALL PRIVILEGES ON DATABASE horizon to $PGUSER;
		GRANT ALL PRIVILEGES ON DATABASE core to $PGUSER;
	SQL

	touch .quickstart-initialized
	popd
}

function init_stellar_core() {
	if [ -f $COREHOME/.core-initialized ]; then
		echo "core: already initialized"
		return 0
	fi
	pushd $COREHOME

	run_silent "chown-core" chown stellar:stellar .
	run_silent "finalize-core-config" sed -ri "s/__PGPASS__/$PGPASS/g" etc/stellar-core.cfg

	start_postgres

	run_silent "init-core-db" sudo -u stellar stellar-core --newdb --conf etc/stellar-core.cfg

	if [ "$NETWORK" == "standalone" ] || [ "$NETWORK" == "bank0" ] || [ "$NETWORK" == "bank1" ] || [ "$NETWORK" == "bank2" ]; then
		run_silent "init-core-scp" sudo -u stellar stellar-core --forcescp --conf etc/stellar-core.cfg
	fi

	touch .core-initialized
	popd
}

function init_horizon() {
	if [ -f $HZHOME/.horizon-initialized ]; then
		echo "horizon: already initialized"
		return 0
	fi
	pushd $HZHOME

	run_silent "chown-horizon" chown stellar:stellar .
	
	sed -ri \
		-e "s/__PGPASS__/$PGPASS/g" \
		-e "s/__NETWORK__/$NETWORK_PASSPHRASE/g" \
		etc/horizon.env

	start_postgres
	run_silent "init-horizon-db" sudo -u stellar ./bin/horizon db init

	touch .horizon-initialized
	popd
}

function init_compliance() {
	if ! [ -d /opt/stellar-default/$NETWORK/compliance ]; then
		echo "compliance: not required"
		return 0
	fi

	if [ -f $COMPLIANCEHOME/.compliance-initialized ]; then
		echo "compliance: already initialized"
		return 0
	fi
	pushd $COMPLIANCEHOME

	run_silent "chown-compliance" chown stellar:stellar .
	
	sed -ri \
		-e "s/__PGPASS__/$PGPASS/g" \
		-e "s/__NETWORK__/$NETWORK_PASSPHRASE/g" \
		etc/compliance.cfg

	start_postgres
	run_silent "init-compliance-db" sudo -u stellar ./bin/compliance -c etc/compliance.cfg --migrate-db

	touch .compliance-initialized
	popd
}

function init_bridge() {
	if ! [ -d /opt/stellar-default/$NETWORK/bridge ]; then
		echo "bridge: not required"
		return 0
	fi
	
	if [ -f $BRIDGEHOME/.bridge-initialized ]; then
		echo "bridge: already initialized"
		return 0
	fi
	pushd $BRIDGEHOME

	run_silent "chown-bridge" chown stellar:stellar .
	
	#run_configure_bridge
	
	sed -ri \
		-e "s/__PGPASS__/$PGPASS/g" \
		-e "s/__NETWORK__/$NETWORK_PASSPHRASE/g" \
		etc/bridge.cfg
	
	start_postgres
	run_silent "init-bridge-db" sudo -u stellar ./bin/bridge -c etc/bridge.cfg --migrate-db

	touch .bridge-initialized
	popd
}

function run_configure_bridge() {

	start_postgres
	start_stellar
	start_horizon

	sleep 120

	#run_silent "generate-issuing-account" node ../scripts/createAccount.js
	node $SCRIPTSHOME/createAccount.js
	export ISSUING_ACCOUNT_FILE=$PWD/issuingAccount.json
	export ISSUING_ACCOUNT_KEY=$(jq '.publicKey' $ISSUING_ACCOUNT_FILE)	

	sed -ri \
		-e "s/__PGPASS__/$PGPASS/g" \
		-e "s/__NETWORK__/$NETWORK_PASSPHRASE/g" \
		-e "s/__ISSUER__/$ISSUING_ACCOUNT_KEY/g" \
		$BRIDGEHOME/etc/bridge.cfg
	
	#run_silent "remove-issuing-account-file" rm -f $ISSUING_ACCOUNT_FILE

	stop_horizon
	stop_stellar

}

function exec_supervisor() {
	echo "starting supervisor"
	exec supervisord -n -c $SUPHOME/etc/supervisord.conf
}

# run_silent is a utility function that runs a command with an abbreviated
# output provided it succeeds.
function run_silent() {
	local LABEL=$1
	shift
	local COMMAND=$1
	shift
	local ARGS=$@
	local OUTFILE="/tmp/run_silent.out"

	echo -n "$LABEL: "
	set +e

	$COMMAND $ARGS &> $OUTFILE

	if [ $? -eq 0 ]; then
    echo "ok"
	else
	  echo "failed!"
		echo ""
		cat $OUTFILE
		exit 1
	fi

	set -e
}

function start_stellar() {
	if [ ! -z "$CURRENT_STELLAR_PID" ]; then
		return 0
	fi

	if [ "$NETWORK" == "standalone" ]; then
		run_silent "init-core-scp" sudo -u stellar stellar-core --forcescp --conf $COREHOME/etc/stellar-core.cfg
	fi

	sudo -u stellar stellar-core --conf $COREHOME/etc/stellar-core.cfg &> /dev/null &
	CURRENT_STELLAR_PID=$!

	#while ! sudo -u stellar stellar-core -c 'info' &> /dev/null; do
	#	echo "Waiting for stellar-core to be available..."
	#	sleep 1
	#done

	echo "stellar-core: up"
}

function stop_stellar() {
	if [ -z "$CURRENT_STELLAR_PID" ]; then
		return 0
	fi

	kill $CURRENT_STELLAR_PID
	# wait for stellar to die
	while kill -0 "$CURRENT_STELLAR_PID" &> /dev/null; do
		sleep 0.5
	done
	echo "stellar-core: down"
}

function start_horizon() {
	if [ ! -z "$CURRENT_HORIZON_PID" ]; then
		return 0
	fi

	sudo -u stellar $HZHOME/bin/horizon serve &> /dev/null &
	CURRENT_HORIZON_PID=$!

	#while ! curl http://localhost:8000 &> /dev/null; do
	#	echo "Waiting for horizon to be available..."
	#	sleep 1
	#done

	echo "horizon: up"
}

function stop_horizon() {
	if [ -z "$CURRENT_HORIZON_PID" ]; then
		return 0
	fi

	kill $CURRENT_HORIZON_PID
	# wait for horizon to die
	while kill -0 "$CURRENT_HORIZON_PID" &> /dev/null; do
		sleep 0.5
	done
	echo "horizon: down"
}

function start_postgres() {
	if [ ! -z "$CURRENT_POSTGRES_PID" ]; then
		return 0
	fi

	sudo -u postgres $PGBIN/postgres -D $PGDATA -c config_file=$PGHOME/etc/postgresql.conf &> /dev/null &
	CURRENT_POSTGRES_PID=$!

	while ! sudo -u postgres psql -c 'select 1' &> /dev/null ; do
	  echo "Waiting for postgres to be available..."
	  sleep 1
	done

	echo "postgres: up"
}

function stop_postgres() {
	if [ -z "$CURRENT_POSTGRES_PID" ]; then
		return 0
	fi

	kill $CURRENT_POSTGRES_PID
	# wait for postgres to die
	while kill -0 "$CURRENT_POSTGRES_PID" &> /dev/null; do
		sleep 0.5
	done
	echo "postgres: down"
}

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

main $@
